### ISSUE TITLE
This is example does not work in IE

### ISSUE THREAD

**Issue by sergsalo** [AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet#3]
I uncommented this:
  //cacheLocation: 'localStorage', // enable this for IE, as sessionStorage does not work for localhost.

but still - it does not work in IE. Chrome works perfectly fine. 

Any help would be greatly appreciated.
Thanks,
Serg

**Comment by sergsalo** [comment]
I meant that the calls to go API do not work and IE

**Comment by ricklang** [comment]
Yes, it doesn't work in IE11 for me too. Chrome is fine. I am working on localhost.

I couldn't even see the HTTPS request in Fiddler when the function $scope.populate calls ToGoAPI service. The function was just pass through, no success/error was returned.

**Comment by ltrain777** [comment]
I hit the same issue with IE11 when testing out the Sample ToGoAPI on localhost.  Chrome is working fine.

**Comment by sergsalo** [comment]
the error i'm getting in log is: 
Error :login_required
Error description:AADSTS50058: User account identifier is not provided.

**Comment by dstrockis** [comment]
Adal.js uses hidden iframes to get tokens for resources other than the SPA's own backend.  That iframe request needs to access the browser's cookies to authenticate with AAD and get the access token.  Unfortunately running in IE on localhost prevents the iframe from accessing the browsers cookies.  So continue to run in chrome, or try deploying to an Azure website to see it work in IE.

I'll add a comment in the sample.  Thanks for pointing this out!
