### ISSUE TITLE
Error - 404

### ISSUE THREAD

**Issue by Neumeier** [AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet#6]
Getting a 404 No Success error code when I followed the steps and downloaded the sample application. The exception is thrown at... 

... using System;
using System.Threading.Tasks;
using Microsoft.Owin;
using Owin;
using Microsoft.Owin.Security.ActiveDirectory;
using System.Configuration;

namespace TodoSPA
{
    public partial class Startup
    {
        public void ConfigureAuth(IAppBuilder app)
        {
            app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Audience = ConfigurationManager.AppSettings["ida:Audience"],
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"]
                });
        }

    }
}

**Comment by Neumeier** [comment]
Manually installing the active directory NuGet from the console line resolved the issue.

**Comment by dstrockis** [comment]
Thanks for reporting @Neumeier, I'll see if I can repro & fix.
